package Hibernate;
// Generated 04-jun-2023 19:02:43 by Hibernate Tools 4.3.1



/**
 * Metodopago generated by hbm2java
 */
public class Metodopago  implements java.io.Serializable {


     private Long id;
     private String idUsuario;
     private String nombre;
     private String detalles;

    public Metodopago() {
    }

    public Metodopago(String idUsuario, String nombre, String detalles) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.detalles = detalles;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }




}


