package Hibernate;
// Generated 30-may-2023 15:55:56 by Hibernate Tools 4.3.1



/**
 * Tarifaenvio generated by hbm2java
 */
public class Tarifaenvio  implements java.io.Serializable {


     private Long id;
     private float precioPeso;
     private float precioVolumen;
     private float precioSeguro;
     private String nombreTarifa;

    public Tarifaenvio() {
    }

    public Tarifaenvio(float precioPeso, float precioVolumen, float precioSeguro, String nombreTarifa) {
       this.precioPeso = precioPeso;
       this.precioVolumen = precioVolumen;
       this.precioSeguro = precioSeguro;
       this.nombreTarifa = nombreTarifa;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public float getPrecioPeso() {
        return this.precioPeso;
    }
    
    public void setPrecioPeso(float precioPeso) {
        this.precioPeso = precioPeso;
    }
    public float getPrecioVolumen() {
        return this.precioVolumen;
    }
    
    public void setPrecioVolumen(float precioVolumen) {
        this.precioVolumen = precioVolumen;
    }
    public float getPrecioSeguro() {
        return this.precioSeguro;
    }
    
    public void setPrecioSeguro(float precioSeguro) {
        this.precioSeguro = precioSeguro;
    }
    public String getNombreTarifa() {
        return this.nombreTarifa;
    }
    
    public void setNombreTarifa(String nombreTarifa) {
        this.nombreTarifa = nombreTarifa;
    }




}


