package Hibernate;
// Generated 30-may-2023 15:55:56 by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String nombre;

    public Categoria() {
    }

    public Categoria(String nombre) {
       this.nombre = nombre;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


