package Hibernate;
// Generated 28-may-2023 20:01:54 by Hibernate Tools 4.3.1



/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private ChatId id;

    public Chat() {
    }

    public Chat(ChatId id) {
       this.id = id;
    }
   
    public ChatId getId() {
        return this.id;
    }
    
    public void setId(ChatId id) {
        this.id = id;
    }




}


