package Hibernate;
// Generated 30-may-2023 15:55:56 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Long id;
     private String direccion;
     private int cp;
     private String nombre;
     private long idUsuario;

    public Direccion() {
    }

    public Direccion(String direccion, int cp, String nombre, long idUsuario) {
       this.direccion = direccion;
       this.cp = cp;
       this.nombre = nombre;
       this.idUsuario = idUsuario;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }




}


