package Hibernate;
// Generated 28-may-2023 20:01:54 by Hibernate Tools 4.3.1



/**
 * Metodopago generated by hbm2java
 */
public class Metodopago  implements java.io.Serializable {


     private Long id;
     private long idUsuario;
     private String ntarjeta;

    public Metodopago() {
    }

    public Metodopago(long idUsuario, String ntarjeta) {
       this.idUsuario = idUsuario;
       this.ntarjeta = ntarjeta;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNtarjeta() {
        return this.ntarjeta;
    }
    
    public void setNtarjeta(String ntarjeta) {
        this.ntarjeta = ntarjeta;
    }




}


