package Hibernate;
// Generated 30-mar-2023 13:28:31 by Hibernate Tools 4.3.1



/**
 * Metodopago generated by hbm2java
 */
public class Metodopago  implements java.io.Serializable {


     private Long id;
     private long idUsuario;
     private long idVenta;

    public Metodopago() {
    }

    public Metodopago(long idUsuario, long idVenta) {
       this.idUsuario = idUsuario;
       this.idVenta = idVenta;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public long getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(long idVenta) {
        this.idVenta = idVenta;
    }




}


