package Hibernate;
// Generated 30-mar-2023 13:28:31 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Long id;
     private String nombre;
     private String descripcion;
     private String estado;
     private String precio;
     private String hastag;

    public Producto() {
    }

    public Producto(String nombre, String descripcion, String estado, String precio, String hastag) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.precio = precio;
       this.hastag = hastag;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public String getHastag() {
        return this.hastag;
    }
    
    public void setHastag(String hastag) {
        this.hastag = hastag;
    }




}


