package Hibernate;
// Generated 30-mar-2023 13:28:31 by Hibernate Tools 4.3.1



/**
 * Puntuacion generated by hbm2java
 */
public class Puntuacion  implements java.io.Serializable {


     private Integer id;
     private int numero;
     private String resenya;

    public Puntuacion() {
    }

    public Puntuacion(int numero, String resenya) {
       this.numero = numero;
       this.resenya = resenya;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getResenya() {
        return this.resenya;
    }
    
    public void setResenya(String resenya) {
        this.resenya = resenya;
    }




}


